### ISSUE TITLE
Learning JS

### ISSUE THREAD

**Issue by louisjordan** [jamesbarrett95/To-Do-Application#1]
Hey man, I couldn't find you on Facebook or LinkedIn so I'm writing here - you can delete it once you've seen it. I'm in your year at Portsmouth but I'm on placement. I just wanted I say I see you're learning some JS and I'd be happy to help if you've got any questions about anything. I'm still learning myself but I definitely think it's a good idea to have someone to  chat with if we have any issue or find any cool stuff to share.

Reply to this if you're interested :+1: 

Speak to you soon :rocket:

**Comment by louisjordan** [comment]
I'm pretty fluent in HTML, CSS and JS with experience with a fair few frameworks (front and back end - jQuery, NodeJS etc) as well as experience with very useful tools to speed up development like Gulp, Sass, PostCSS, Babel.

**Comment by jamesbarrett95** [comment]
Hey dude!

Thanks for the email, always good to hear this sort of stuff. Funnily enough I've actually deleted my Facebook, along with my Snapchat and Instagram (part of my new years resolution 😄) so that's probably the reason you couldn't reach me as quick as you could!

I'm currently on placement too! It's not incredibly involved with JavaScript, mostly HTML, CSS and BootStrap, however it's pretty good. Learnt a few new things such as SASS and Gulp (however I've now been told to move onto Webpack... Bloody JavaScript.).

At the moment I'm just brushing up on my Vanilla JS, doing little mini projects as you may have seen on my GitHub. Then I think I'm going to tackle the social networking site again as my 2nd year attempt was just... not sure how to finish that sentence. Let's just say I barely scraped a pass haha.

But yeah! I will stop waffling, I'm definitely up for sharing some stuff and will ask any questions if need be.

What's your placement like? Enjoying it? And you got ideas for your final year project yet?

Look forward to hearing from you (email me at james-barrett@hotmail.com)!

James.

**Comment by louisjordan** [comment]
Emailed you :+1: we should set up some easy way of contact like an IM or something

**Comment by louisjordan** [comment]
Ima close this
